spring:
  devtools:
    restart:
      enabled: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/rms
    username: postgres
    password: 1234
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
        format_sql: true
logging:
  file:
    name: rms.log
  level:
    root: INFO
